### ISSUE TITLE
Comments Are Dropped in the Vistor Method

### ISSUE THREAD

**Issue by bmoore813** [joshtemple/lkml#69]
I was looking at using this for CI and my use case would be to automatically add a description field if its not populated in the lookml for any dimension. The issue is when I read in the lookml file and add that description field to a dimension we lose all the comments that are important for us to maintain the code base since the `DictVisitor().visitor(tree)` doesn't return the comments even though they're in the tree structure. Is it possible to keep the comments so we can consider using this in our CI pipeline?

**Comment by joshtemple** [comment]
Hey Brian, that's correct. In simple parsing mode, lkml doesn't preserve whitespace or comments. Simple parsing is more for generating new LookML from scratch or testing but not modifying existing LookML.

To do that, you need to operate on the parse tree, which preserves everything. It's a little bit more complex to work with because it's a tree structure and not JSON-like.

I've written up some examples of traversing and modifying the parse tree in [the docs here](https://lkml.readthedocs.io/en/latest/advanced.html#modifying-the-parse-tree-with-transformers). Give it a read and see if you can figure out how to proceed.

You'll want to create a subclass of BasicTransformer that, when visiting BlockNodes, adds a PairNode for the description where necessary.

It's possible I haven't explained things well enough in the docs, so I'd definitely appreciate your feedback.
